language: python
python:
- '3.6'
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  app: heroku-babla
  api_key: 21f347b5-3c4e-470f-8591-3cbff3a40c4d
  
